In [1]:
import matplotlib

In [2]:
len(dir(matplotlib))

109

In [3]:
import matplotlib.pyplot as plt

In [4]:
len(dir(matplotlib))

172

- import 하는 것마다 쓸 수 있는 양이 많아진다

In [5]:
class B:
    def __repr__(self):
        return '졸리다'
    def __str__(self):
        return '진짜졸려'

In [6]:
b = B()

In [7]:
b

졸리다

In [8]:
print(b)

진짜졸려

In [8]:
class X:
    def __getattr__(self, attr):
        if attr == 'a':
            return '문근영2'
        return '문근영'

In [5]:
a = X()

In [6]:
a.a

'문근영2'

In [20]:
a.b

'문근영'

-----------------------------

In [22]:
a = 1.0

In [23]:
getattr(a, 'hex')()

'0x1.0000000000000p+0'

-----------------------

In [24]:
import seaborn as sns

In [25]:
tips = sns.load_dataset('tips')

In [26]:
# issubclass 상속받았는지 확인할 수 있자나!
# 또는 getitem 체크!

'__getitem__' in dir(tips)

True

In [28]:
for i in tips.iterrows():
    print(i)

(0, total_bill     16.99
tip             1.01
sex           Female
smoker            No
day              Sun
time          Dinner
size               2
Name: 0, dtype: object)
(1, total_bill     10.34
tip             1.66
sex             Male
smoker            No
day              Sun
time          Dinner
size               3
Name: 1, dtype: object)
(2, total_bill     21.01
tip              3.5
sex             Male
smoker            No
day              Sun
time          Dinner
size               3
Name: 2, dtype: object)
(3, total_bill     23.68
tip             3.31
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 3, dtype: object)
(4, total_bill     24.59
tip             3.61
sex           Female
smoker            No
day              Sun
time          Dinner
size               4
Name: 4, dtype: object)
(5, total_bill     25.29
tip             4.71
sex             Male
smoker            No
day              Sun
time          Dinner
size               4
Name: 5, dtype: object)
(6, total_bill      8.77
tip                2
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 6, dtype: object)
(7, total_bill     26.88
tip             3.12
sex             Male
smoker            No
day              Sun
time          Dinner
size               4
Name: 7, dtype: object)
(8, total_bill     15.04
tip             1.96
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 8, dtype: object)
(9, total_bill     14.78
tip             3.23
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 9, dtype: object)
(10, total_bill     10.27
tip             1.71
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 10, dtype: object)
(11, total_bill     35.26
tip                5
sex           Female
smoker            No
day              Sun
time          Dinner
size               4
Name: 11, dtype: object)
(12, total_bill     15.42
tip             1.57
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 12, dtype: object)
(13, total_bill     18.43
tip                3
sex             Male
smoker            No
day              Sun
time          Dinner
size               4
Name: 13, dtype: object)
(14, total_bill     14.83
tip             3.02
sex           Female
smoker            No
day              Sun
time          Dinner
size               2
Name: 14, dtype: object)
(15, total_bill     21.58
tip             3.92
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 15, dtype: object)
(16, total_bill     10.33
tip             1.67
sex           Female
smoker            No
day              Sun
time          Dinner
size               3
Name: 16, dtype: object)
(17, total_bill     16.29
tip             3.71
sex             Male
smoker            No
day              Sun
time          Dinner
size               3
Name: 17, dtype: object)
(18, total_bill     16.97
tip              3.5
sex           Female
smoker            No
day              Sun
time          Dinner
size               3
Name: 18, dtype: object)
(19, total_bill     20.65
tip             3.35
sex             Male
smoker            No
day              Sat
time          Dinner
size               3
Name: 19, dtype: object)
(20, total_bill     17.92
tip             4.08
sex             Male
smoker            No
day              Sat
time          Dinner
size               2
Name: 20, dtype: object)
(21, total_bill     20.29
tip             2.75
sex           Female
smoker            No
day              Sat
time          Dinner
size               2
Name: 21, dtype: object)
(22, total_bill     15.77
tip             2.23
sex           Female
smoker            No
day              Sat
time          Dinner
size               2
Name: 22, dtype: object)
(23, total_bill     39.42
tip             7.58
sex             Male
smoker            No
day              Sat
time          Dinner
size               4
Name: 23, dtype: object)
(24, total_bill     19.82
tip             3.18
sex             Male
smoker            No
day              Sat
time          Dinner
size               2
Name: 24, dtype: object)
(25, total_bill     17.81
tip             2.34
sex             Male
smoker            No
day              Sat
time          Dinner
size               4
Name: 25, dtype: object)
(26, total_bill     13.37
tip                2
sex             Male
smoker            No
day              Sat
time          Dinner
size               2
Name: 26, dtype: object)
(27, total_bill     12.69
tip                2
sex             Male
smoker            No
day              Sat
time          Dinner
size               2
Name: 27, dtype: object)
(28, total_bill      21.7
tip              4.3
sex             Male
smoker            No
day              Sat
time          Dinner
size               2
Name: 28, dtype: object)
(29, total_bill     19.65
tip                3
sex           Female
smoker            No
day              Sat
time          Dinner
size               2
Name: 29, dtype: object)
(30, total_bill      9.55
tip             1.45
sex             Male
smoker            No
day              Sat
time          Dinner
size               2
Name: 30, dtype: object)
(31, total_bill     18.35
tip              2.5
sex             Male
smoker            No
day              Sat
time          Dinner
size               4
Name: 31, dtype: object)
(32, total_bill     15.06
tip                3
sex           Female
smoker            No
day              Sat
time          Dinner
size               2
Name: 32, dtype: object)
(33, total_bill     20.69
tip             2.45
sex           Female
smoker            No
day              Sat
time          Dinner
size               4
Name: 33, dtype: object)
(34, total_bill     17.78
tip             3.27
sex             Male
smoker            No
day              Sat
time          Dinner
size               2
Name: 34, dtype: object)
(35, total_bill     24.06
tip              3.6
sex             Male
smoker            No
day              Sat
time          Dinner
size               3
Name: 35, dtype: object)
(36, total_bill     16.31
tip                2
sex             Male
smoker            No
day              Sat
time          Dinner
size               3
Name: 36, dtype: object)
(37, total_bill     16.93
tip             3.07
sex           Female
smoker            No
day              Sat
time          Dinner
size               3
Name: 37, dtype: object)
(38, total_bill     18.69
tip             2.31
sex             Male
smoker            No
day              Sat
time          Dinner
size               3
Name: 38, dtype: object)
(39, total_bill     31.27
tip                5
sex             Male
smoker            No
day              Sat
time          Dinner
size               3
Name: 39, dtype: object)
(40, total_bill     16.04
tip             2.24
sex             Male
smoker            No
day              Sat
time          Dinner
size               3
Name: 40, dtype: object)
(41, total_bill     17.46
tip             2.54
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 41, dtype: object)
(42, total_bill     13.94
tip             3.06
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 42, dtype: object)
(43, total_bill      9.68
tip             1.32
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 43, dtype: object)
(44, total_bill      30.4
tip              5.6
sex             Male
smoker            No
day              Sun
time          Dinner
size               4
Name: 44, dtype: object)
(45, total_bill     18.29
tip                3
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 45, dtype: object)
(46, total_bill     22.23
tip                5
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 46, dtype: object)
(47, total_bill      32.4
tip                6
sex             Male
smoker            No
day              Sun
time          Dinner
size               4
Name: 47, dtype: object)
(48, total_bill     28.55
tip             2.05
sex             Male
smoker            No
day              Sun
time          Dinner
size               3
Name: 48, dtype: object)
(49, total_bill     18.04
tip                3
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 49, dtype: object)
(50, total_bill     12.54
tip              2.5
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 50, dtype: object)
(51, total_bill     10.29
tip              2.6
sex           Female
smoker            No
day              Sun
time          Dinner
size               2
Name: 51, dtype: object)
(52, total_bill     34.81
tip              5.2
sex           Female
smoker            No
day              Sun
time          Dinner
size               4
Name: 52, dtype: object)
(53, total_bill      9.94
tip             1.56
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 53, dtype: object)
(54, total_bill     25.56
tip             4.34
sex             Male
smoker            No
day              Sun
time          Dinner
size               4
Name: 54, dtype: object)
(55, total_bill     19.49
tip             3.51
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 55, dtype: object)
(56, total_bill     38.01
tip                3
sex             Male
smoker           Yes
day              Sat
time          Dinner
size               4
Name: 56, dtype: object)
(57, total_bill     26.41
tip              1.5
sex           Female
smoker            No
day              Sat
time          Dinner
size               2
Name: 57, dtype: object)
(58, total_bill     11.24
tip             1.76
sex             Male
smoker           Yes
day              Sat
time          Dinner
size               2
Name: 58, dtype: object)
(59, total_bill     48.27
tip             6.73
sex             Male
smoker            No
day              Sat
time          Dinner
size               4
Name: 59, dtype: object)
(60, total_bill     20.29
tip             3.21
sex             Male
smoker           Yes
day              Sat
time          Dinner
size               2
Name: 60, dtype: object)
(61, total_bill     13.81
tip                2
sex             Male
smoker           Yes
day              Sat
time          Dinner
size               2
Name: 61, dtype: object)
(62, total_bill     11.02
tip             1.98
sex             Male
smoker           Yes
day              Sat
time          Dinner
size               2
Name: 62, dtype: object)
(63, total_bill     18.29
tip             3.76
sex             Male
smoker           Yes
day              Sat
time          Dinner
size               4
Name: 63, dtype: object)
(64, total_bill     17.59
tip             2.64
sex             Male
smoker            No
day              Sat
time          Dinner
size               3
Name: 64, dtype: object)
(65, total_bill     20.08
tip             3.15
sex             Male
smoker            No
day              Sat
time          Dinner
size               3
Name: 65, dtype: object)
(66, total_bill     16.45
tip             2.47
sex           Female
smoker            No
day              Sat
time          Dinner
size               2
Name: 66, dtype: object)
(67, total_bill      3.07
tip                1
sex           Female
smoker           Yes
day              Sat
time          Dinner
size               1
Name: 67, dtype: object)
(68, total_bill     20.23
tip             2.01
sex             Male
smoker            No
day              Sat
time          Dinner
size               2
Name: 68, dtype: object)
(69, total_bill     15.01
tip             2.09
sex             Male
smoker           Yes
day              Sat
time          Dinner
size               2
Name: 69, dtype: object)
(70, total_bill     12.02
tip             1.97
sex             Male
smoker            No
day              Sat
time          Dinner
size               2
Name: 70, dtype: object)
(71, total_bill     17.07
tip                3
sex           Female
smoker            No
day              Sat
time          Dinner
size               3
Name: 71, dtype: object)
(72, total_bill     26.86
tip             3.14
sex           Female
smoker           Yes
day              Sat
time          Dinner
size               2
Name: 72, dtype: object)
(73, total_bill     25.28
tip                5
sex           Female
smoker           Yes
day              Sat
time          Dinner
size               2
Name: 73, dtype: object)
(74, total_bill     14.73
tip              2.2
sex           Female
smoker            No
day              Sat
time          Dinner
size               2
Name: 74, dtype: object)
(75, total_bill     10.51
tip             1.25
sex             Male
smoker            No
day              Sat
time          Dinner
size               2
Name: 75, dtype: object)
(76, total_bill     17.92
tip             3.08
sex             Male
smoker           Yes
day              Sat
time          Dinner
size               2
Name: 76, dtype: object)
(77, total_bill     27.2
tip               4
sex            Male
smoker           No
day            Thur
time          Lunch
size              4
Name: 77, dtype: object)
(78, total_bill    22.76
tip               3
sex            Male
smoker           No
day            Thur
time          Lunch
size              2
Name: 78, dtype: object)
(79, total_bill    17.29
tip            2.71
sex            Male
smoker           No
day            Thur
time          Lunch
size              2
Name: 79, dtype: object)
(80, total_bill    19.44
tip               3
sex            Male
smoker          Yes
day            Thur
time          Lunch
size              2
Name: 80, dtype: object)
(81, total_bill    16.66
tip             3.4
sex            Male
smoker           No
day            Thur
time          Lunch
size              2
Name: 81, dtype: object)
(82, total_bill     10.07
tip             1.83
sex           Female
smoker            No
day             Thur
time           Lunch
size               1
Name: 82, dtype: object)
(83, total_bill    32.68
tip               5
sex            Male
smoker          Yes
day            Thur
time          Lunch
size              2
Name: 83, dtype: object)
(84, total_bill    15.98
tip            2.03
sex            Male
smoker           No
day            Thur
time          Lunch
size              2
Name: 84, dtype: object)
(85, total_bill     34.83
tip             5.17
sex           Female
smoker            No
day             Thur
time           Lunch
size               4
Name: 85, dtype: object)
(86, total_bill    13.03
tip               2
sex            Male
smoker           No
day            Thur
time          Lunch
size              2
Name: 86, dtype: object)
(87, total_bill    18.28
tip               4
sex            Male
smoker           No
day            Thur
time          Lunch
size              2
Name: 87, dtype: object)
(88, total_bill    24.71
tip            5.85
sex            Male
smoker           No
day            Thur
time          Lunch
size              2
Name: 88, dtype: object)
(89, total_bill    21.16
tip               3
sex            Male
smoker           No
day            Thur
time          Lunch
size              2
Name: 89, dtype: object)
(90, total_bill     28.97
tip                3
sex             Male
smoker           Yes
day              Fri
time          Dinner
size               2
Name: 90, dtype: object)
(91, total_bill     22.49
tip              3.5
sex             Male
smoker            No
day              Fri
time          Dinner
size               2
Name: 91, dtype: object)
(92, total_bill      5.75
tip                1
sex           Female
smoker           Yes
day              Fri
time          Dinner
size               2
Name: 92, dtype: object)
(93, total_bill     16.32
tip              4.3
sex           Female
smoker           Yes
day              Fri
time          Dinner
size               2
Name: 93, dtype: object)
(94, total_bill     22.75
tip             3.25
sex           Female
smoker            No
day              Fri
time          Dinner
size               2
Name: 94, dtype: object)
(95, total_bill     40.17
tip             4.73
sex             Male
smoker           Yes
day              Fri
time          Dinner
size               4
Name: 95, dtype: object)
(96, total_bill     27.28
tip                4
sex             Male
smoker           Yes
day              Fri
time          Dinner
size               2
Name: 96, dtype: object)
(97, total_bill     12.03
tip              1.5
sex             Male
smoker           Yes
day              Fri
time          Dinner
size               2
Name: 97, dtype: object)
(98, total_bill     21.01
tip                3
sex             Male
smoker           Yes
day              Fri
time          Dinner
size               2
Name: 98, dtype: object)
(99, total_bill     12.46
tip              1.5
sex             Male
smoker            No
day              Fri
time          Dinner
size               2
Name: 99, dtype: object)
(100, total_bill     11.35
tip              2.5
sex           Female
smoker           Yes
day              Fri
time          Dinner
size               2
Name: 100, dtype: object)
(101, total_bill     15.38
tip                3
sex           Female
smoker           Yes
day              Fri
time          Dinner
size               2
Name: 101, dtype: object)
(102, total_bill      44.3
tip              2.5
sex           Female
smoker           Yes
day              Sat
time          Dinner
size               3
Name: 102, dtype: object)
(103, total_bill     22.42
tip             3.48
sex           Female
smoker           Yes
day              Sat
time          Dinner
size               2
Name: 103, dtype: object)
(104, total_bill     20.92
tip             4.08
sex           Female
smoker            No
day              Sat
time          Dinner
size               2
Name: 104, dtype: object)
(105, total_bill     15.36
tip             1.64
sex             Male
smoker           Yes
day              Sat
time          Dinner
size               2
Name: 105, dtype: object)
(106, total_bill     20.49
tip             4.06
sex             Male
smoker           Yes
day              Sat
time          Dinner
size               2
Name: 106, dtype: object)
(107, total_bill     25.21
tip             4.29
sex             Male
smoker           Yes
day              Sat
time          Dinner
size               2
Name: 107, dtype: object)
(108, total_bill     18.24
tip             3.76
sex             Male
smoker            No
day              Sat
time          Dinner
size               2
Name: 108, dtype: object)
(109, total_bill     14.31
tip                4
sex           Female
smoker           Yes
day              Sat
time          Dinner
size               2
Name: 109, dtype: object)
(110, total_bill        14
tip                3
sex             Male
smoker            No
day              Sat
time          Dinner
size               2
Name: 110, dtype: object)
(111, total_bill      7.25
tip                1
sex           Female
smoker            No
day              Sat
time          Dinner
size               1
Name: 111, dtype: object)
(112, total_bill     38.07
tip                4
sex             Male
smoker            No
day              Sun
time          Dinner
size               3
Name: 112, dtype: object)
(113, total_bill     23.95
tip             2.55
sex             Male